name: Prose Linting

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prose-lint
        with:
          linter: 'proselint'  # or 'write-good'
